org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true

minecraftVersion=1.21.1
neoVersion=21.1.227
parchmentMinecraftVersion=1.21.1
parchmentMappingsVersion=2024.11.17

modId=appliedhistory
modName=Applied History
modVersion=0.2.0
modGroup=net.meatwo310.appliedhistory
modAuthors=ArthurGuo
modDescription=Adds RS2-style last-modified history rows to AE2 terminals.

