org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=true

minecraftVersion=26.1.2
neoVersion=26.1.2.43-beta

modId=appliedhistory
modName=Applied History
modVersion=1.0.1
modGroup=net.aichichikuwa.appliedhistory
modAuthors=ArthurGuo
modDescription=Adds RS2-style last-modified history rows to AE2 terminals.

